site_name: Notes on Anything
site_author: Rafi Darmawan
site_url: https://drmwnrafi.github.io/notesonanything/

theme:
  name : material
  logo : assets/media/notesx.png
  favicon : assets/media/ziczac.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/moon 
        name: Switch to dark mode
      primary: white
      accent: lime 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: fontawesome/solid/sun 
        name: Switch to light mode    
      primary: black
      accent: lime
  font:
      text: Roboto Mono

plugins:
  - social
  - search
  - mermaid2
  - panzoom:
      mermaid: true
      full_screen: True
      key: "none"

extra:
  extra_shadow_root_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/drmwnrafi
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/drmwnnrafi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/drmwnnrafi/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

extra_javascript:
  # other extra java script
  - assets/js/mathjax-config.js
  - assets/js/card.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - assets/css/extra.css
  - assets/css/card.css
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css