site_name: Notes on Anything
site_author: Rafi Darmawan
site_url: https://drmwnrafi.github.io/notesonanything/

theme:
  name : material
  logo : assets/media/notesx.png
  favicon : assets/media/ziczac.png
  custom_dir: overrides
  features:
    - announce.dismiss
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/moon 
        name: Switch to dark mode
      primary: white
      accent: deep orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: fontawesome/solid/sun 
        name: Switch to light mode    
      primary: black
      accent: lime
  font:
      text: Montserrat

plugins:
  - social
  - search
  - autorefs

extra:
  extra_shadow_root_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/drmwnrafi
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/drmwnnrafi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/drmwnnrafi/
  # generator: false

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.blocks.caption
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.superfences:
  #     custom_fences:
        # - name: mermaid
        #   class: mermaid
        #   format: !!python/name:mermaid2.fence_mermaid_custom

extra_javascript:
  - assets/js/mathjax-config.js
  - assets/js/card.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - assets/css/extra.css
  - assets/css/card.css
#   - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

nav :
  - index.md
  - Mathematics : 
    - Preface : maths/preface.md
    - Probability :
      - Intro to Probability : maths/probability/intro_probs.md
      - Set Theory : maths/probability/set_theory.md
      - Binomial and Multinomial Distribution : maths/probability/binom_dist.md
      - Conditional Distribution : maths/probability/conditional_probs.md
      - Laws of Total Probability : maths/probability/total_probs.md
      - Bayes' Theorem : maths/probability/bayes_theorem.md
      - Independence : maths/probability/independence.md
      - Random Variabels : maths/probability/random_var.md
      - Bernouli Distribution : maths/probability/bernouli.md
      - Binomial to Normal Distribution : maths/probability/binomial_normal.md
      - Binomial to Poisson Distribution : maths/probability/binomial_poisson.md
      - Geometric Distribution : maths/probability/geo_dist.md
      - Exponential Distribution : maths/probability/exp_dist.md
      - Poisson Proccess : maths/probability/poisson_proccess.md
      - Gamma Distribution : maths/probability/gamma_dist.md
      - Function of Random Variables : maths/probability/func_random.md
      - Joint Distribution : maths/probability/joint_dist.md
      - Theory of Expectation : maths/probability/expected.md
      - Variance and Standart Deviation : maths/probability/var_std.md
      - Markov's Inequality : maths/probability/markov_ieq.md
      - Chebyshev Inequality : maths/probability/chebyshev_ieq.md
      - Laws of Large Number : maths/probability/large_num.md
      - Moment Generating Function : maths/probability/moment_func.md
      - Lebesgue Measure : maths/probability/lebesgue.md
      - Covariance and Correlation : maths/probability/cov_corr.md
      - Tail Sum : maths/probability/tail_sum.md
      - Central Limit Theorem : maths/probability/clf.md
    - Optimization :
      - Least Squares : maths/optimization/lsqrt.md
      - Non-Linear Least Squares : maths/optimization/non_lsqrt.md
      - Approximation of Hessian : maths/optimization/approx_hessian.md
      - Optimization Procedure :
        - Gradient-Descent : maths/optimization/grad_descent.md
        - Newton-Rapshon : maths/optimization/newt_rapshon.md
        - Gauss-Newton : maths/optimization/gauss_newt.md
        - Levenberg Marquardt : maths/optimization/lm.md
    - Algebra :
      - Singular Value Decomposition : maths/algebra/svd.md
      - Frobenius Inner Product : maths/algebra/frobenius_inner.md
    - Lie Theory :
      - Preface : maths/lie_theory/preface.md
      - Lie Groups : maths/lie_theory/lie_groups.md
      - Lie Algebra : maths/lie_theory/lie_algebra.md
      - Adjoint : maths/lie_theory/adjoint.md

  - Artificial Intelligences :
    - Preface : AI/preface.md
    - Attention Mechanism :
      - Additive Attention :  AI/attention/add_att.md
      - Dot Product Attention : AI/attention/dot_att.md
      - Scaled-Dot Product Attention : AI/attention/scaled_dot_att.md
      - Multi Head Attention : AI/attention/mha.md
      - Multi Query Attention : AI/attention/mqa.md
      - Grouped Query Attention : AI/attention/gqa.md
    - Models :
      - Large Language Models :
        - LLAMA-2 : AI/model/llama2.md
        - JPEG-LM : AI/model/jpeg-lm.md
      - Computer Vision :
        - U-Net : AI/model/u_net.md
        - U2-Net : AI/model/u2_net.md
    - Tokenizers :
        - Byte-Pair Encoding : AI/tokenizer/bpe.md

  - Robotics :
    - Preface : robotics/preface.md
    - Equations of Motion :
      - Quadcopter Dynamics: robotics/models_sys/quadcopter.md
    - Nonlinear Control :
      - Applied Nonlinear Control :
        - Introduction to Nonlinear Systems: robotics/nonlinear_control/intro.md
        - Phase Plane Analysis : robotics/nonlinear_control/phase_plane.md
      - Geometric Control on SE(3) : robotics/nonlinear_control/geom_quadcopter.md
    - Sensor Fusion :
      - Kalman Filter : robotics/sensor_fusion/kf.md
      - Extended Kalman Filter : robotics/sensor_fusion/ekf.md
    - SLAM:
      - Point to Point Iterative Closest Point : robotics/slam/icp.md
      - Point to Line Iterative Closest Point : robotics/slam/plicp.md
      - Pose-Graph : robotics/slam/pose_graph.md